#!/usr/bin/env bash

MACHINE_FILTER=${1-"120-unix-lab"}

test_home=Classes/Spring_18/CS455/HW2-PC/CS455-HW2-PC

for i in `cat machine_list`
do
    for value in {1..7}
    do
	echo 'logging into '${i}
	dbus-launch gnome-terminal -- bash -c "ssh -t ${i} 'cd ${test_home};java cs455.scaling.client.Client richmond 4444 4;bash;'" &
    done
done
